### ISSUE TITLE
【图管理】-创建图时一些异常提示

### ISSUE THREAD

**Issue by cuijiling** [hugegraph/hugegraph-hubble#13]
BUG复现步骤：

创建图->填写内容后点击创建
![image](https://user-images.githubusercontent.com/54136425/63083997-c0065080-bf7c-11e9-978a-210c60c223fc.png)

期望结果：有合理提示

实际结果：异常提示，不知道哪里错误
![image](https://user-images.githubusercontent.com/54136425/63084011-c85e8b80-bf7c-11e9-9aec-1ad0e2f1f469.png)

**Comment by Linary** [comment]
duplicate as #18
