### ISSUE TITLE
gremlin查询、鼠标双击、鼠标右击筛选等 接口查询显示错误

### ISSUE THREAD

**Issue by lixiaobiao** [hugegraph/hugegraph-hubble#17]
复现：
1、选用正常connection_id字段，输入正确的gremlin查询语言，访问接口 结果访问正常，内容展示正常
2、选用不正常connection_id字段或者connection_id不存在，输入正确的gremlin查询语言访问接口。结果接口仍然可访问，没有报错信息
如图：
<img width="914" alt="bug" src="https://user-images.githubusercontent.com/52277518/63147663-69a71980-c031-11e9-9352-1bd844fcf024.png">

期望：
connection_id字段为必填项，缺失或这输入信息错误，应该报错。

**Comment by Linary** [comment]
已修复
