### ISSUE TITLE
【图管理】-编辑修改图名称后点击保存报错。

### ISSUE THREAD

**Issue by cuijiling** [hugegraph/hugegraph-hubble#18]
前提条件：创建一个图

操作步骤：编辑一个图，编辑图名称->编辑后点击保存

期望结果：成功保存

实际结果：提示报错
![image](https://user-images.githubusercontent.com/54136425/63150023-45027000-c038-11e9-8633-1f8de3bf1007.png)

**Comment by Linary** [comment]
修改提示为：“不存在名字为 xxx 的图在服务 localhost:8080 上”
