### ISSUE TITLE
hubble-fe模块打包失败

### ISSUE THREAD

**Issue by dropping** [hugegraph/hugegraph-hubble#226]
@baidu/one-ui 找不到
getaddrinfo ENOTFOUND registry.npm.baidu-int.com

**Comment by GeorgeHon** [comment]
+1

**Comment by gitriver** [comment]
+1

**Comment by Linary** [comment]
one-ui是我司内部的组件库，未开源，所以会打包失败。目前hubble还未发布，发布后会解决此问题。

**Comment by PegasusLiang** [comment]
> one-ui是我司内部的组件库，未开源，所以会打包失败。目前hubble还未发布，发布后会解决此问题。

请问预计到什么时候开源发布呢。

**Comment by imbajin** [comment]
> > one-ui 是我司内部的组件库，未开源，所以会打包失败。目前 hubble 还未发布，发布后会解决此问题。
> 
> 请问预计到什么时候开源发布呢。

已经全部替换为开源组件, 欢迎使用, master 分支代码即可编译, 欢迎反馈
