### ISSUE TITLE
【图管理】-图列表中对任意图双击"删除"button后弹出2个删除确认框。

### ISSUE THREAD

**Issue by cuijiling** [hugegraph/hugegraph-hubble#23]
前提条件：存在一个图

操作步骤：图中点击"更多"->双击"删除" button

期望结果：弹出一个删除提示框

实际结果：弹出2个删除提示框

备注：双击"编辑" button,不会弹出2个编辑框

**Comment by OshotOkill** [comment]
组件库默认将 dropdown 的层级设置为 1051，modal 的蒙层层级为 1040，所以目前 dropdown 在 modal 蒙层上面

**Comment by cuijiling** [comment]
已修复

**Comment by cuijiling** [comment]
已修复
