### ISSUE TITLE
有使用教程吗？

### ISSUE THREAD

**Issue by lingxingzhang** [hugegraph/hugegraph-hubble#234]
有使用教程吗？

**Comment by DeathWH** [comment]
> 有使用教程吗？

老哥，求个安装包，感谢！！！官方的下载链接失效了……

**Comment by javeme** [comment]
@lingxingzhang 教程请参考：https://hugegraph.github.io/hugegraph-doc/quickstart/hugegraph-hubble.html

@DeathWH 正式版吧还没有上传，预计下周会上传。如果着急的话可以关注HugeGraph公众号获取beta版本。

**Comment by HFatBird** [comment]
> @lingxingzhang 教程请参考：https://hugegraph.github.io/hugegraph-doc/quickstart/hugegraph-hubble.html
> 
> @DeathWH 正式版本还没有上传，预计下周会上传。如果着急的话可以关注HugeGraph公众号获取beta版本。

您好，我看到了官网发布了正式版本的压缩包，但是部署教程是还没有发布吗？试着启动hubble，然后nginx代理部署前端，然后映射了/api路径后，看到了页面，但是页面功能会报错...
