### ISSUE TITLE
hubble-fe 使用yarn编译不了,registry.npm.baidu-int.com不能访问

### ISSUE THREAD

**Issue by gitriver** [hugegraph/hugegraph-hubble#237]
yarn  install
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "http://registry.npm.baidu-int.com/create-react-class/-/create-react-class-15.6.3.tgz: getaddrinfo EAI_AGAIN registry.npm.baidu-int.com registry.npm.baidu-int.com:80".
info If you think this is a bug, please open a bug report with the information provided in "/root/hugegraph-hubble/hubble-fe/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...

**Comment by Linary** [comment]
#226

**Comment by Neo-Chaos** [comment]
因为他的依赖库是百度私有库,你当然无法找到

**Comment by imbajin** [comment]
> 因为他的依赖库是百度私有库，你当然无法找到

最新的 master 分支代码已经替换为了全开源的 ant-ui, 后端适配的代码也都完成了, 之后可以直接 mvn 编译整个项目和测试.  欢迎参与~
