### ISSUE TITLE
【图管理】-高亮关键字的搜索结果顺序错误

### ISSUE THREAD

**Issue by cuijiling** [hugegraph/hugegraph-hubble#24]
操作步骤：搜索框中输入任意关键字，如数字3

期望结果：搜索结果顺序为图ID > 图名称

实际结果：图名称> 图ID 
![image](https://user-images.githubusercontent.com/54136425/63255231-df1c1f80-c2a7-11e9-8cb6-a0f50d94d4e9.png)

**Comment by Linary** [comment]
已修改，请验证。

**Comment by cuijiling** [comment]
已修复
