### ISSUE TITLE
@baidu/one-ui找不到

### ISSUE THREAD

**Issue by youngkangrui** [hugegraph/hugegraph-hubble#254]
包找不到，能上传下不

**Comment by javeme** [comment]
@youngkangrui 即将会发布hubble的release版本，依赖的one-ui因为目前未开源，所以只能先使用release版本。

**Comment by foxFallingSkies** [comment]
> @youngkangrui 即将会发布hubble的release版本，依赖的one-ui因为目前未开源，所以只能先使用release版本。

给开源下呗。这样这个项目就能运行看了

**Comment by javeme** [comment]
@foxFallingSkies one-ui 是基础组件库，属于其它部门的产品，所以得看他们的节奏合适开源。以后我们会升级适配 one-ui 的二进制包方式来管理依赖。

**Comment by chaomashi** [comment]
@javeme 您好我想知道什么时候会升级适配 one-ui 的二进制包方式来管理依赖

**Comment by leestorm** [comment]
@javeme 麻烦问下现在代码的开源是什么状态了？完全开源还是依然有内部组件为开源？

**Comment by Linary** [comment]
one-ui 仍然是未开源的

**Comment by wanganjuan** [comment]
https://github.com/hugegraph/hugegraph-hubble/pull/343

**Comment by zhuyanchao5186** [comment]
截止2022年2月2日，编译hubbble-fe出错，
Not Found - GET https://registry.npmjs.org/@baidu%2fone-ui - Not found，请问什么时间可以开源@baidu one-ui ？

**Comment by imbajin** [comment]
> 截止 2022 年 2 月 2 日，编译 hubbble-fe 出错， Not Found - GET [registry.npmjs.org/@baidu%2fone-ui](https://registry.npmjs.org/@baidu%2fone-ui) - Not found，请问什么时间可以开源 @baidu one-ui ？

参考社区最新 PR #344 , 目前采用 Ant-UI 代替闭源版本, 欢迎关注

**Comment by zhuyanchao5186** [comment]
> > 截止 2022 年 2 月 2 日，编译 hubbble-fe 出错， Not Found - GET [registry.npmjs.org/@baidu%2fone-ui](https://registry.npmjs.org/@baidu%2fone-ui) - Not found，请问什么时间可以开源 @baidu one-ui ？
> 
> 参考社区最新 PR #344 , 目前采用 Ant-UI 代替闭源版本, 欢迎关注

非常感谢
