### ISSUE TITLE
取 hugegraph-hubble-1.5.0.tar.gz  404

### ISSUE THREAD

**Issue by zdsec999** [hugegraph/hugegraph-hubble#262]
https://github.com/hugegraph/hugegraph-hubble/releases/download/v1.5.0/hugegraph-hubble-1.5.0.tar.gz

**Comment by DeathWH** [comment]
刚还下载2MB多，然后就404了，啥情况啊

**Comment by 352174109** [comment]
而且前端都不能编译了

**Comment by javeme** [comment]
正式版本还没有上传，预计下周会上传。如果着急的话可以关注HugeGraph公众号获取beta版本。

**Comment by Linary** [comment]
现在可以下载了。
