### ISSUE TITLE
未找到tar.gz包

### ISSUE THREAD

**Issue by HFatBird** [hugegraph/hugegraph-hubble#273]
#262 ，官网教程下载页面 https://hugegraph.github.io/hugegraph-doc/download.html 中提供的下载链接无法进行下载

**Comment by lipengyu** [comment]
有没有解决方案呢？

**Comment by HFatBird** [comment]
> 有没有解决方案呢？

这能有啥方案...等开发人员放上去这些文件吧 :-)

**Comment by javeme** [comment]
@HFatBird @lipengyu 接下来一周会把安装包上传。目前也可以从交流群获取beta版本，关注HugeGraph公众号可以加入交流群。
