### ISSUE TITLE
【图管理】-主机名填写错误时提示不合理。

### ISSUE THREAD

**Issue by cuijiling** [hugegraph/hugegraph-hubble#28]
操作步骤：创建一个图->主机名输入错误 "10.103.169.24e"->点击保存

期望结果：有合理提示

实际结果：提示: Failed to do request
![image](https://user-images.githubusercontent.com/54136425/63329399-747ce980-c364-11e9-929b-7d0d37d14f3b.png)

**Comment by Linary** [comment]
已修复，请验证。

```
{
  	"name": "test4",
  	"graph" : "hugegraph",
	"host" : "10.10.10.10e",
	"port" : 8080
}
```

```
{
"status": 400,
"data": null,
"message": "未知的主机名 10.10.10.10e"
}
```

**Comment by cuijiling** [comment]
已修复
