### ISSUE TITLE
没有安装和运行文档吗

### ISSUE THREAD

**Issue by xiaoxiaopingzi** [hugegraph/hugegraph-hubble#284]
https://hugegraph.github.io/hugegraph-doc/quickstart/hugegraph-hubble.html 只有使用文档，没有安装和运行的文档

**Comment by javeme** [comment]
@xiaoxiaopingzi  解压tar包后，得到hugegraph-hubble-1.5.0文件夹，进入该目录，执行`bin/start-hubble.sh`脚本启动即可。

**Comment by ak43zhang** [comment]
我直接安装后卡在初始化，页面空白

**Comment by Linary** [comment]
服务启动成功了吗，截个图看下。

**Comment by qiuliangwen** [comment]
如下图，我的情况应该和他一样的，也是卡在Spring DispatcherServlet这里，页面无法访问。
![image](https://user-images.githubusercontent.com/60164759/103628580-3349a180-4f7a-11eb-9667-46d38054d978.png)

**Comment by roamerop** [comment]
remember change the `server.host`  to your ip in conf/hugegraph-hubble.properties, by default localhost, then restart-hubble

**Comment by Linary** [comment]
Thanks for @roamerop
