### ISSUE TITLE
【图管理】-更多中"编辑" 和 "删除" 2个 button没有居中对齐

### ISSUE THREAD

**Issue by cuijiling** [hugegraph/hugegraph-hubble#29]
操作步骤： 任意图后面点击"更多" button，查看"编辑" 和 "删除" 2个 button显示

期望结果：正常居中显示

实际结果：没有居中显示
![image](https://user-images.githubusercontent.com/54136425/63329534-b9088500-c364-11e9-92aa-ce4a21229955.png)

**Comment by OshotOkill** [comment]
组件库的问题，等待相关人员修复

**Comment by cuijiling** [comment]
已修复
