### ISSUE TITLE
【图管理】创建一个有用户名和密码的图，密码故意输入错误后多次点击创建，出现多个提示框。

### ISSUE THREAD

**Issue by cuijiling** [hugegraph/hugegraph-hubble#30]
操作步骤：创建一个有用户名和密码的图，密码故意输入错误->多次点击创建

期望结果：只有一个提示

实际结果：出现多个提示
![image](https://user-images.githubusercontent.com/54136425/63415384-449b1800-c430-11e9-9547-21715516155d.png)

**Comment by dongpeiguo** [comment]
该结果符合预期
