### ISSUE TITLE
[Question] use valueMap()  error

### ISSUE THREAD

**Issue by s348268281** [hugegraph/hugegraph-hubble#318]
## Environment ( 环境信息 - 必填 )
- **Server Version**: v0.11.2
- **Backend**: Cassandra 3.x, 1 nodes, HDD
- **OS**: 
- **Data Size**:  10 vertices, 10 edges 

## Your Question ( 问题描述 )

当我在studio使用语句g.V().valueMap() 时，报错
Error!
java.util.ArrayList cannot be cast to java.lang.String
请问是需要数据符合什么标准吗？我的数据就是几个简单的测试数据。

**Comment by Linary** [comment]
看起来这个是hubble的bug，没能兼容到valueMap这个step返回的数据类型。
