### ISSUE TITLE
[Bug] hubble在添加顶点时，如果顶点属性较多需要翻页时下滑输入框会错位

### ISSUE THREAD

**Issue by ttybupt** [hugegraph/hugegraph-hubble#320]
### Bug Type (问题类型)

dashboard render (前端渲染问题)

### Before submit

- [X] 我已经确认现有的 [Server-Issues](https://github.com/hugegraph/hugegraph/issues) 与 [Hubble-Issues](https://github.com/hugegraph/hugegraph-hubble/issues) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.0
- Hubble Version: v1.5
- Data Size:  1w vertices, 1w edges 

### Expected & Actual behavior (期望与实际表现)

https://user-images.githubusercontent.com/17845489/124751430-350c1600-df59-11eb-9c2b-2382f0286cf3.mov

见上面的录屏

添加顶点，下拉之后输入框不会跟着划动，会产生错位

**Comment by imbajin** [comment]
另外补充一下还有个比较严重的 bug 就是属性名稍长一些无法展开或者看到全部名字, 例如

<img width="991" alt="image" src="https://user-images.githubusercontent.com/17706099/160743126-8978c45a-e0ba-4a02-94aa-023d6841c39f.png">


@wanganjuan 可以帮忙看看是前端的问题, 好修复么感谢~

**Comment by wanganjuan** [comment]
fixed https://github.com/hugegraph/hugegraph-hubble/pull/364
