### ISSUE TITLE
Hugegraph hubble ot working in 0.12.0 version

### ISSUE THREAD

**Issue by KirubakaranSP** [hugegraph/hugegraph-hubble#337]
### Problem Type (问题类型)

others (please edit later)

### Before submit

- [X] 我已经确认现有的 [Issues](https://github.com/hugegraph/hugegraph/issues) 与 [FAQ](https://hugegraph.github.io/hugegraph-doc/guides/faq.html) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Backend: RocksDB x nodes, HDD or SSD 
- OS: xx CPUs, xx G RAM, Centos 7.x 
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

Hugegraph hubble is not working when connecting with hugegraph server version 0.12.0.It throws version mismatch. 

Error : The version of hugegraph-client and hugegraph-server don't match.
Help me on this!!

**Comment by imbajin** [comment]
@KirubakaranSP forget to remind you that the new [package](https://github.com/hugegraph/hugegraph-hubble/releases/download/v1.6.0/hugegraph-hubble-1.6.0.tar.gz)(V0.12) has been released, and it supports unlimited graph bindings. U can also follow the release information for further updates
