### ISSUE TITLE
代码编译报错

### ISSUE THREAD

**Issue by wuchaojing** [hugegraph/hugegraph-hubble#354]
### Problem Type (问题类型)

exception / error (异常报错)

### Before submit

- [X] 我已经确认现有的 [Server-Issues](https://github.com/hugegraph/hugegraph/issues) 与 [Hubble-Issues](https://github.com/hugegraph/hugegraph-hubble/issues) 中没有相同 / 重复问题

### Environment (环境信息)

java 1.8
maven 3.8.1
yarn

### Your Question (问题描述)

![image](https://user-images.githubusercontent.com/37741352/156087153-5c93047a-4d6d-4dff-b9ca-a5f4c5c44916.png)

把代码拉下来并且配置好环境（java/mvn/yarn）后，编译报错，辛苦帮看看原因。

**Comment by imbajin** [comment]
编译在本地 ci 里已经跑通, 应该还是比较稳定的, 确认一下以下几点:
1. 编译所在路径是否在 hubble 根目录
2. 编译命令 (可参考 ci 文件)
3. 打开 -e -X 输出详细报错信息

**Comment by wuchaojing** [comment]
问题已解决

**Comment by imbajin** [comment]
> 问题已解决

嗯呐, 可以附一下你解决问题的方式和原因. 方便其他同学也可以参考多谢~  

另外也欢迎二次开发改进后提交相关 PR, 😄

**Comment by wuchaojing** [comment]
> > 问题已解决
> 
> 嗯呐, 可以附一下你解决问题的方式和原因. 方便其他同学也可以参考多谢~
> 
> 另外也欢迎二次开发改进后提交相关 PR, 😄

感觉回复~  我本地执行mvn clean package install -Dmaven.test.skip=true 就会报那个错。把install去掉，只package就好了
