### ISSUE TITLE
请问，最新版本的hubble会取消掉社区版图上限3个的限制么？

### ISSUE THREAD

**Issue by thomasg19930417** [hugegraph/hugegraph-hubble#358]
### Before submit

- [X] 我已经确认现有的 [Server-Issues](https://github.com/hugegraph/hugegraph/issues) 与 [Hubble-Issues](https://github.com/hugegraph/hugegraph-hubble/issues) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.11.x
- Hubble Version: v1.x
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

![image](https://user-images.githubusercontent.com/20243868/158723185-5ce34ea6-3728-4d59-9f9b-395ca5a73bc6.png)
用master 分支的代码看已经没有了图上限的限制

**Comment by imbajin** [comment]
是的, 之后稳定后会推出一个正式的包发布 1.6.5, 并且从这个版本开始也没有前端的闭源包问题了. 欢迎使用和参与贡献

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/17706099/158726406-12da800b-d6ff-4498-b52e-8aaf5a06782f.png">

**Comment by thomasg19930417** [comment]
收到，感谢回复。

**Comment by thomasg19930417** [comment]
> 是的, 之后稳定后会推出一个正式的包发布 1.6.5, 并且从这个版本开始也没有前端的闭源包问题了. 欢迎使用和参与贡献
> 
> <img alt="image" width="1071" src="https://user-images.githubusercontent.com/17706099/158726406-12da800b-d6ff-4498-b52e-8aaf5a06782f.png">
收到，感谢回复。
