### ISSUE TITLE
编译master分支生成的hubble，执行算法分析中的算法报网络异常，请重新再试，是不支持算法分析吗

### ISSUE THREAD

**Issue by songlf1002** [hugegraph/hugegraph-hubble#360]
### Problem Type (问题类型)

exception / error (异常报错)

### Before submit

- [X] 我已经确认现有的 [Server-Issues](https://github.com/hugegraph/hugegraph/issues) 与 [Hubble-Issues](https://github.com/hugegraph/hugegraph-hubble/issues) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.0
- Hubble Version: v1.6
- Data Size:  xx vertices, xx edges 

### Your Question (问题描述)

编译master分支生成的hubble，执行算法分析中的算法报网络异常，请重新再试，是不支持算法分析吗
![image](https://user-images.githubusercontent.com/70573089/159887363-3510c172-fd61-4d1c-b263-75a45ff6a08f.png)

**Comment by imbajin** [comment]
tp 算法暂时没有发布, 等稳定版发布可用
