### ISSUE TITLE
traversers使用shortestpath报错：{"exception":"class java.lang.OutOfMemoryError","message":"Java heap space","cause":""}

### ISSUE THREAD

**Issue by HumanHero** [hugegraph/hugegraph-hubble#375]
### Problem Type (问题类型)

exception / error (异常报错)

### Before submit

- [x] 我已经确认现有的 [Server-Issues](https://github.com/hugegraph/hugegraph/issues) 与 [Hubble-Issues](https://github.com/hugegraph/hugegraph-hubble/issues) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: v0.12.0
- Hubble Version: v1.6.5

### Your Question (问题描述)

http://192.168.64.1:8080/graphs/hugegraph/traversers/paths?source="
3:XXXXX1"&target="3:XXXX2"&max_depth=5

可正常查询出数据

http://192.168.64.1:8080/graphs/hugegraph/traversers/shortestpath?source="
3:XXXXX1"&target="3:XXXX2"&max_depth=5

返回错误
{"exception":"class java.lang.OutOfMemoryError","message":"Java heap space","cause":""}

**Comment by imbajin** [comment]
refer #371,  please move to apache hugegraph-toolchain please

**Comment by HumanHero** [comment]
> ### Problem Type (问题类型)
> exception / error (异常报错)
> 
> ### 提交前
> * [x]  我已经确认现有的 [Server-Issues](https://github.com/hugegraph/hugegraph/issues) 与 [Hubble-Issues](https://github.com/hugegraph/hugegraph-hubble/issues) 中没有相同 / 重复问题
> 
> ### Environment (环境信息)
> * 服务器版本：v0.12.0
> * 哈勃版本：v1.6.5
> 
> ### Your Question (问题描述)
> http://192.168.64.1:8080/graphs/hugegraph/traversers/paths?source= " 3:XXXXX1"&target="3:XXXX2"&max_depth=5
> 
> 可正常查询出数据
> 
> http://192.168.64.1:8080/graphs/hugegraph/traversers/shortestpath?source= " 3:XXXXX1"&target="3:XXXX2"&max_depth=5
> 
> 返回错误 {"exception":"class java.lang.OutOfMemoryError","message":"Java heap space","cause":""}
> 
> ### Vertex/Edge example (问题点 / 边数据举例)
> _没有反应_
> 
> ### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)
> _没有反应_
