### ISSUE TITLE
【Gremlin语句查询】-Gremlin语句查询界面"执行"和"收藏" button 置灰状态时，鼠标定位后提示"查询语句不能为空" 时点击空白处不消失

### ISSUE THREAD

**Issue by cuijiling** [hugegraph/hugegraph-hubble#38]
操作步骤：访问任意图，鼠标定位到"执行" 或 "收藏"处 -> 提示"查询语句不能为空" ->点击空白处

期望结果：提示语消失

实际结果：提示语不消失
![image](https://user-images.githubusercontent.com/54136425/64104217-6b4d3d00-cda6-11e9-94a3-e76fd6156bcc.png)

**Comment by OshotOkill** [comment]
此处在开发和生产环境下产生的 html 不一致(⊙o⊙)? 生产环境下不生成包裹的 `span` 元素导致 tooltip hover 逻辑异常

**Comment by OshotOkill** [comment]
此处在开发和生产环境下产生的 html 不一致(⊙o⊙)? 生产环境下不生成包裹的 `span` 元素导致 tooltip hover 逻辑异常

**Comment by OshotOkill** [comment]
以查明是组件库根据 `element.type` 和 `element.type.name` 来判断 dom 元素和组件名，而生产环境下它们被替换成 `function` 和混淆过的短命名（如 `n`）

**Comment by cuijiling** [comment]
test ok
