### ISSUE TITLE
【图链接】创建图链接（无host || host为空时）接口返回值有误

### ISSUE THREAD

**Issue by lixiaobiao** [hugegraph/hugegraph-hubble#5]
<img width="748" alt="hostIp" src="https://user-images.githubusercontent.com/52277518/62366469-8cc5c980-b559-11e9-9e38-daf5d10e63a2.png">

缺失host
提示：the parameter of  host does not exist and does nor null
缺失ip
提示：the parameter of  ip does not exist and does nor null

**Comment by lixiaobiao** [comment]
<img width="711" alt="屏幕快照 2019-08-02 下午7 35 14" src="https://user-images.githubusercontent.com/52277518/62367578-ad435300-b55c-11e9-85b4-b4dad11830dd.png">
缺少两个参数后仍然报错信息仍然有错

**Comment by Linary** [comment]
已修复
