### ISSUE TITLE
【sidebar】优化点击区域

### ISSUE THREAD

**Issue by dongpeiguo** [hugegraph/hugegraph-hubble#51]
![image](https://user-images.githubusercontent.com/18440603/64336787-6986b200-d010-11e9-8d24-bdfa43793abd.png)
![image](https://user-images.githubusercontent.com/18440603/64336807-786d6480-d010-11e9-9aee-2edd13aa23a0.png)
预期点击返回图管理/折叠sidebar点击区域非icon，应为整行

**Comment by lincitan** [comment]
新提测版本，侧边导航栏这两个区域应该在hover态时才出现底色

**Comment by OshotOkill** [comment]
要设置 hover 呈现该颜色

**Comment by dongpeiguo** [comment]
190925验收通过
