### ISSUE TITLE
【收藏语句】输入框报错位置有误

### ISSUE THREAD

**Issue by dongpeiguo** [hugegraph/hugegraph-hubble#52]
![image](https://user-images.githubusercontent.com/18440603/64338949-7954c500-d015-11e9-90e7-b00b723d3407.png)
![image](https://user-images.githubusercontent.com/18440603/64339072-c0db5100-d015-11e9-9a31-0a14945123bc.png)
![image](https://user-images.githubusercontent.com/18440603/64597199-e1295800-d3e7-11e9-9bfb-a3bc29798b02.png)

气泡内输入框报错应出现在输入框下方
![image](https://user-images.githubusercontent.com/18440603/64338983-8b366800-d015-11e9-8ea4-ffc6cee1c051.png)

**Comment by dongpeiguo** [comment]
190924验收
未修复

![image](https://user-images.githubusercontent.com/18440603/65478816-bd711200-debd-11e9-9577-21593a3f272b.png)

![image](https://user-images.githubusercontent.com/18440603/65479127-e0e88c80-debe-11e9-84f0-9d4ee07f5c74.png)

**Comment by OshotOkill** [comment]
目前设置不输入或者超过48字符，收藏置灰。

错误提示使用 <Alert /> 组件，放置在 <Input /> 下方

**Comment by dongpeiguo** [comment]
出现格式错误时，使用输入框错误提示样式

预期：
语句名允许字母、数字、中文、下划线
![image](https://user-images.githubusercontent.com/18440603/65567208-ee1d7e00-df87-11e9-859f-26537d1b8135.png)

实际：
![image](https://user-images.githubusercontent.com/18440603/65567198-e2ca5280-df87-11e9-86ce-4bc81c30480e.png)
