### ISSUE TITLE
【图链接】name&graph搜索结果没有起效果，都为全部展示

### ISSUE THREAD

**Issue by lixiaobiao** [hugegraph/hugegraph-hubble#6]
<img width="899" alt="屏幕快照 2019-08-02 下午7 30 28" src="https://user-images.githubusercontent.com/52277518/62367381-0f4f8880-b55c-11e9-8583-c92be9df569f.png">
<img width="750" alt="屏幕快照 2019-08-02 下午7 30 47" src="https://user-images.githubusercontent.com/52277518/62367385-11194c00-b55c-11e9-84a9-4d0b1f237447.png">

**Comment by Linary** [comment]
已修复
