### ISSUE TITLE
【Gremlin语句查询】不输入任何东西，收藏应该置灰

### ISSUE THREAD

**Issue by cuijiling** [hugegraph/hugegraph-hubble#65]
操作步骤：执行一Gremlin语句后，点击收藏，不输入任何内容

期望结果：弹框中“收藏” button 置灰

实际结果：弹框中“收藏” button 没有置灰
![image](https://user-images.githubusercontent.com/54136425/64604210-57cc5280-d3f4-11e9-8015-f17858d4d79b.png)

**Comment by OshotOkill** [comment]
前端在这里会对输入的内容做简单校验，如果未存在字符，数字或者下划线则收藏和执行置灰

**Comment by cuijiling** [comment]
test ok
