### ISSUE TITLE
【Gremlin语句查询】-Gremlin语句输入语句输入一空行时也能执行成功。

### ISSUE THREAD

**Issue by cuijiling** [hugegraph/hugegraph-hubble#66]
操作步骤：Gremlin语句输入一空行后执行

结果：也能执行成功
![image](https://user-images.githubusercontent.com/54136425/64604293-79c5d500-d3f4-11e9-8c4b-0ac3ed11bf3a.png)

**Comment by OshotOkill** [comment]
Duplicate #65
