### ISSUE TITLE
【Gremlin语句查询】查询语句超过5000条时不能收藏

### ISSUE THREAD

**Issue by cuijiling** [hugegraph/hugegraph-hubble#69]
操作步骤：执行查询语句g.V().limit(20) 超过5000个

结果：执行后提示超时，点击收藏，不能收藏
![image](https://user-images.githubusercontent.com/54136425/64604435-b98cbc80-d3f4-11e9-91b0-819e80a9d3b8.png)

**Comment by lxb1111** [comment]
ok
