### ISSUE TITLE
【图结果展示】图展示、表格展示、jsontab下点击全屏后，文字未显示为“退出全屏”

### ISSUE THREAD

**Issue by xiaohan520507** [hugegraph/hugegraph-hubble#75]
BUG复现步骤：

1、打开任意一个图库
2、观察图结果展示区域
3、点击功能键全屏

期望结果：
点击全屏后，文字能显示为“退出全屏”

实际结果：
点击全屏后，文字显示为“退出”

**Comment by OshotOkill** [comment]
新查看最新版本设计稿

![image](https://user-images.githubusercontent.com/6079112/65027661-560f0b80-d96d-11e9-8f76-a2a56a8abe13.png)
