### ISSUE TITLE
【侧边导航】左侧切换图库，收藏的语句内容未同步更新

### ISSUE THREAD

**Issue by xiaohan520507** [hugegraph/hugegraph-hubble#77]
BUG复现步骤：

1、当前图库129
2、切换到图库89，能显示89的收藏语句
3、再切回到129，无法显示129对应的收藏语句

期望结果：
左侧切换图库，收藏的语句内容能同步更新

实际结果：
左侧切换图库，收藏的语句内容未同步更新

**Comment by OshotOkill** [comment]
确认目前的版本所有 id 共用相同的执行记录和收藏语句
