### ISSUE TITLE
【收藏的查询】空格、标点符号等都能被收藏

### ISSUE THREAD

**Issue by xiaohan520507** [hugegraph/hugegraph-hubble#79]
BUG复现步骤：

1、执行语句编辑框里输入任意字符或空格等
2、确认无法执行，但能点击收藏

期望结果：
标点符号及空格等无法收藏，或者说无法执行的语句无法收藏

实际结果：
空格、标点符号等都能被收藏
![空格标点都能被收藏](https://user-images.githubusercontent.com/31171896/64751652-6f6c1e00-d54f-11e9-9111-85978eef6177.JPG)

**Comment by OshotOkill** [comment]
Duplicate #65
