### ISSUE TITLE
【访问图】-图展示icon 与UE不一致

### ISSUE THREAD

**Issue by cuijiling** [hugegraph/hugegraph-hubble#82]
操作步骤：访问图，查看左侧图展示icon

期望结果：与UE一致

实际结果：与UE不一致
![image](https://user-images.githubusercontent.com/54136425/65019666-450ace00-d95e-11e9-8e62-0c971eadb5ab.png)

**Comment by OshotOkill** [comment]
请查看最新版本的设计稿

![image](https://user-images.githubusercontent.com/6079112/65027492-03355400-d96d-11e9-8b38-b5cfd0b7e406.png)
