### ISSUE TITLE
分页器-统一位置居卡片右侧

### ISSUE THREAD

**Issue by lincitan** [hugegraph/hugegraph-hubble#95]
![image](https://user-images.githubusercontent.com/54930229/65479063-8b13e480-debe-11e9-8457-862c3d5dbe20.png)
![image](https://user-images.githubusercontent.com/54930229/65479088-a8e14980-debe-11e9-9855-9c655a931926.png)

**Comment by OshotOkill** [comment]
清除缓存重新查看

**Comment by lincitan** [comment]
9.25号验收，通过
