### ISSUE TITLE
收藏查询翻页器有误

### ISSUE THREAD

**Issue by dongpeiguo** [hugegraph/hugegraph-hubble#96]
应和执行记录保持一致

![image](https://user-images.githubusercontent.com/18440603/65479276-5eac9800-debf-11e9-9e2b-e1dd12aa8bcf.png)

![image](https://user-images.githubusercontent.com/18440603/65479299-73892b80-debf-11e9-8b51-dd1a4e1b4291.png)

**Comment by OshotOkill** [comment]
清除缓存重新查看

**Comment by dongpeiguo** [comment]
清除缓存后无bug
