### ISSUE TITLE
在未输入查询语句时-文字btn颜色不正确

### ISSUE THREAD

**Issue by lincitan** [hugegraph/hugegraph-hubble#97]
![image](https://user-images.githubusercontent.com/54930229/65479273-5d7b6b00-debf-11e9-9da9-c6137b6bacb4.png)
![image](https://user-images.githubusercontent.com/54930229/65479322-8bf94600-debf-11e9-97a7-081b73d010c0.png)

**Comment by OshotOkill** [comment]
已确认 @lincitan 下个版本删除文字，目前版本无需改动
